// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.6.1
// source: proto/user-post.proto

package user_post

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{0}
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{1}
}

type MakeCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserId   string `protobuf:"bytes,1,opt,name=FromUserId,proto3" json:"FromUserId,omitempty"`
	ToUserId     string `protobuf:"bytes,2,opt,name=ToUserId,proto3" json:"ToUserId,omitempty"`
	Content      string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	PostId       uint32 `protobuf:"varint,4,opt,name=PostId,proto3" json:"PostId,omitempty"`
	IsTop        bool   `protobuf:"varint,5,opt,name=IsTop,proto3" json:"IsTop,omitempty"`
	TopCommentId uint32 `protobuf:"varint,6,opt,name=TopCommentId,proto3" json:"TopCommentId,omitempty"`
	Title        string `protobuf:"bytes,7,opt,name=Title,proto3" json:"Title,omitempty"`
	Avatar       string `protobuf:"bytes,8,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (x *MakeCommentRequest) Reset() {
	*x = MakeCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeCommentRequest) ProtoMessage() {}

func (x *MakeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeCommentRequest.ProtoReflect.Descriptor instead.
func (*MakeCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{2}
}

func (x *MakeCommentRequest) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *MakeCommentRequest) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *MakeCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MakeCommentRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *MakeCommentRequest) GetIsTop() bool {
	if x != nil {
		return x.IsTop
	}
	return false
}

func (x *MakeCommentRequest) GetTopCommentId() uint32 {
	if x != nil {
		return x.TopCommentId
	}
	return 0
}

func (x *MakeCommentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MakeCommentRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId uint32 `protobuf:"varint,1,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCommentRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetCommentOfPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Page   uint32 `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit  uint32 `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *GetCommentOfPostRequest) Reset() {
	*x = GetCommentOfPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentOfPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentOfPostRequest) ProtoMessage() {}

func (x *GetCommentOfPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentOfPostRequest.ProtoReflect.Descriptor instead.
func (*GetCommentOfPostRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommentOfPostRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *GetCommentOfPostRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentOfPostRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId  uint32 `protobuf:"varint,1,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	FromUserId string `protobuf:"bytes,2,opt,name=FromUserId,proto3" json:"FromUserId,omitempty"`
	ToUserId   string `protobuf:"bytes,3,opt,name=ToUserId,proto3" json:"ToUserId,omitempty"`
	Content    string `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateTime string `protobuf:"bytes,5,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{5}
}

func (x *CommentResponse) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *CommentResponse) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *CommentResponse) GetToUserId() string {
	if x != nil {
		return x.ToUserId
	}
	return ""
}

func (x *CommentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type TopCommentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommentId  uint32             `protobuf:"varint,1,opt,name=CommentId,proto3" json:"CommentId,omitempty"`
	FromUserId string             `protobuf:"bytes,2,opt,name=FromUserId,proto3" json:"FromUserId,omitempty"`
	Content    string             `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	CreateTime string             `protobuf:"bytes,4,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Comments   []*CommentResponse `protobuf:"bytes,5,rep,name=Comments,proto3" json:"Comments,omitempty"`
}

func (x *TopCommentResponse) Reset() {
	*x = TopCommentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopCommentResponse) ProtoMessage() {}

func (x *TopCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopCommentResponse.ProtoReflect.Descriptor instead.
func (*TopCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{6}
}

func (x *TopCommentResponse) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *TopCommentResponse) GetFromUserId() string {
	if x != nil {
		return x.FromUserId
	}
	return ""
}

func (x *TopCommentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TopCommentResponse) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *TopCommentResponse) GetComments() []*CommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

type CommentOfPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId   uint32                `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Comments []*TopCommentResponse `protobuf:"bytes,2,rep,name=Comments,proto3" json:"Comments,omitempty"`
}

func (x *CommentOfPostResponse) Reset() {
	*x = CommentOfPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommentOfPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentOfPostResponse) ProtoMessage() {}

func (x *CommentOfPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentOfPostResponse.ProtoReflect.Descriptor instead.
func (*CommentOfPostResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{7}
}

func (x *CommentOfPostResponse) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CommentOfPostResponse) GetComments() []*TopCommentResponse {
	if x != nil {
		return x.Comments
	}
	return nil
}

type MakeLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId  uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Avatar  string `protobuf:"bytes,4,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
}

func (x *MakeLikeRequest) Reset() {
	*x = MakeLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeLikeRequest) ProtoMessage() {}

func (x *MakeLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeLikeRequest.ProtoReflect.Descriptor instead.
func (*MakeLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{8}
}

func (x *MakeLikeRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *MakeLikeRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MakeLikeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MakeLikeRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type CancelLikeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId  uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Account string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
}

func (x *CancelLikeRequest) Reset() {
	*x = CancelLikeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLikeRequest) ProtoMessage() {}

func (x *CancelLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLikeRequest.ProtoReflect.Descriptor instead.
func (*CancelLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{9}
}

func (x *CancelLikeRequest) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *CancelLikeRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type LikeOfUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Page    int32  `protobuf:"varint,2,opt,name=Page,proto3" json:"Page,omitempty"`
	Limit   int32  `protobuf:"varint,3,opt,name=Limit,proto3" json:"Limit,omitempty"`
}

func (x *LikeOfUserRequest) Reset() {
	*x = LikeOfUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeOfUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeOfUserRequest) ProtoMessage() {}

func (x *LikeOfUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeOfUserRequest.ProtoReflect.Descriptor instead.
func (*LikeOfUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{10}
}

func (x *LikeOfUserRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LikeOfUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *LikeOfUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LikeOfUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	PostIds []uint32 `protobuf:"varint,2,rep,packed,name=PostIds,proto3" json:"PostIds,omitempty"`
}

func (x *LikeOfUserResponse) Reset() {
	*x = LikeOfUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeOfUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeOfUserResponse) ProtoMessage() {}

func (x *LikeOfUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeOfUserResponse.ProtoReflect.Descriptor instead.
func (*LikeOfUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{11}
}

func (x *LikeOfUserResponse) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LikeOfUserResponse) GetPostIds() []uint32 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

type LikeStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PostId uint32 `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	Liked  bool   `protobuf:"varint,2,opt,name=Liked,proto3" json:"Liked,omitempty"`
}

func (x *LikeStatus) Reset() {
	*x = LikeStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LikeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeStatus) ProtoMessage() {}

func (x *LikeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeStatus.ProtoReflect.Descriptor instead.
func (*LikeStatus) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{12}
}

func (x *LikeStatus) GetPostId() uint32 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *LikeStatus) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type BactchLikedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	PostIds []uint32 `protobuf:"varint,2,rep,packed,name=PostIds,proto3" json:"PostIds,omitempty"`
}

func (x *BactchLikedRequest) Reset() {
	*x = BactchLikedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BactchLikedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BactchLikedRequest) ProtoMessage() {}

func (x *BactchLikedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BactchLikedRequest.ProtoReflect.Descriptor instead.
func (*BactchLikedRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{13}
}

func (x *BactchLikedRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BactchLikedRequest) GetPostIds() []uint32 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

type BatchLikedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string        `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Status  []*LikeStatus `protobuf:"bytes,2,rep,name=Status,proto3" json:"Status,omitempty"`
}

func (x *BatchLikedResponse) Reset() {
	*x = BatchLikedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_user_post_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchLikedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchLikedResponse) ProtoMessage() {}

func (x *BatchLikedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_post_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchLikedResponse.ProtoReflect.Descriptor instead.
func (*BatchLikedResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_post_proto_rawDescGZIP(), []int{14}
}

func (x *BatchLikedResponse) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BatchLikedResponse) GetStatus() []*LikeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_proto_user_post_proto protoreflect.FileDescriptor

var file_proto_user_post_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6f,
	0x73, 0x74, 0x22, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xea, 0x01, 0x0a, 0x12, 0x4d, 0x61,
	0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x54, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x73, 0x54, 0x6f, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x49,
	0x73, 0x54, 0x6f, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x54, 0x6f, 0x70, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x34, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xa5, 0x01, 0x0a, 0x0f, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x46,
	0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x54,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x54,
	0x6f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x22, 0xc4, 0x01, 0x0a, 0x12, 0x54, 0x6f, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x72, 0x6f, 0x6d, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x72, 0x6f, 0x6d,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x36, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x6a, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x4f, 0x66, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x08, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x70, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x71, 0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x65, 0x4c, 0x69, 0x6b, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x45, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x50, 0x6f,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x57,
	0x0a, 0x11, 0x4c, 0x69, 0x6b, 0x65, 0x4f, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x48, 0x0a, 0x12, 0x4c, 0x69, 0x6b, 0x65, 0x4f,
	0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x49,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x73, 0x22, 0x3a, 0x0a, 0x0a, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x22, 0x48, 0x0a,
	0x12, 0x42, 0x61, 0x63, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07,
	0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x73, 0x22, 0x5d, 0x0a, 0x12, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70,
	0x6f, 0x73, 0x74, 0x2e, 0x4c, 0x69, 0x6b, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xf6, 0x02, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x6f, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0b, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x4d,
	0x61, 0x6b, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x5a, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4f,
	0x66, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x66, 0x50,
	0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x08, 0x4d, 0x61, 0x6b, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x73,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0a,
	0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x1c, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4c, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x70, 0x6f, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x70, 0x6f, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_user_post_proto_rawDescOnce sync.Once
	file_proto_user_post_proto_rawDescData = file_proto_user_post_proto_rawDesc
)

func file_proto_user_post_proto_rawDescGZIP() []byte {
	file_proto_user_post_proto_rawDescOnce.Do(func() {
		file_proto_user_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_user_post_proto_rawDescData)
	})
	return file_proto_user_post_proto_rawDescData
}

var file_proto_user_post_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_user_post_proto_goTypes = []interface{}{
	(*Request)(nil),                 // 0: user_post.Request
	(*Response)(nil),                // 1: user_post.Response
	(*MakeCommentRequest)(nil),      // 2: user_post.MakeCommentRequest
	(*DeleteCommentRequest)(nil),    // 3: user_post.DeleteCommentRequest
	(*GetCommentOfPostRequest)(nil), // 4: user_post.GetCommentOfPostRequest
	(*CommentResponse)(nil),         // 5: user_post.CommentResponse
	(*TopCommentResponse)(nil),      // 6: user_post.TopCommentResponse
	(*CommentOfPostResponse)(nil),   // 7: user_post.CommentOfPostResponse
	(*MakeLikeRequest)(nil),         // 8: user_post.MakeLikeRequest
	(*CancelLikeRequest)(nil),       // 9: user_post.CancelLikeRequest
	(*LikeOfUserRequest)(nil),       // 10: user_post.LikeOfUserRequest
	(*LikeOfUserResponse)(nil),      // 11: user_post.LikeOfUserResponse
	(*LikeStatus)(nil),              // 12: user_post.LikeStatus
	(*BactchLikedRequest)(nil),      // 13: user_post.BactchLikedRequest
	(*BatchLikedResponse)(nil),      // 14: user_post.BatchLikedResponse
}
var file_proto_user_post_proto_depIdxs = []int32{
	5,  // 0: user_post.TopCommentResponse.Comments:type_name -> user_post.CommentResponse
	6,  // 1: user_post.CommentOfPostResponse.Comments:type_name -> user_post.TopCommentResponse
	12, // 2: user_post.BatchLikedResponse.Status:type_name -> user_post.LikeStatus
	2,  // 3: user_post.UserPost.MakeComment:input_type -> user_post.MakeCommentRequest
	3,  // 4: user_post.UserPost.DeleteComment:input_type -> user_post.DeleteCommentRequest
	4,  // 5: user_post.UserPost.GetCommentOfPost:input_type -> user_post.GetCommentOfPostRequest
	8,  // 6: user_post.UserPost.MakeLike:input_type -> user_post.MakeLikeRequest
	9,  // 7: user_post.UserPost.CancelLike:input_type -> user_post.CancelLikeRequest
	1,  // 8: user_post.UserPost.MakeComment:output_type -> user_post.Response
	1,  // 9: user_post.UserPost.DeleteComment:output_type -> user_post.Response
	7,  // 10: user_post.UserPost.GetCommentOfPost:output_type -> user_post.CommentOfPostResponse
	1,  // 11: user_post.UserPost.MakeLike:output_type -> user_post.Response
	1,  // 12: user_post.UserPost.CancelLike:output_type -> user_post.Response
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_user_post_proto_init() }
func file_proto_user_post_proto_init() {
	if File_proto_user_post_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_user_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCommentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentOfPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopCommentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommentOfPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelLikeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeOfUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeOfUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LikeStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BactchLikedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_user_post_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchLikedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_user_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_post_proto_goTypes,
		DependencyIndexes: file_proto_user_post_proto_depIdxs,
		MessageInfos:      file_proto_user_post_proto_msgTypes,
	}.Build()
	File_proto_user_post_proto = out.File
	file_proto_user_post_proto_rawDesc = nil
	file_proto_user_post_proto_goTypes = nil
	file_proto_user_post_proto_depIdxs = nil
}
