database:
  dsn: "root:root@123@tcp(db:3306)/user_service?charset=utf8&parseTime=True&loc=Local"
micro:
  service: "userService"
  version: "latest"
server:
  address: "127.0.0.1:80"
user:
  avatar: ""