database:
  dsn: "root:Root@123@tcp(139.196.30.123:3306)/inn?charset=utf8&parseTime=True&loc=Local"
micro:
  service: "userService"
  version: "latest"
server:
  http:
    address: "127.0.0.1:8081"
user:
  default_avatar: ""