database:
  dsn: "root:root@tcp(139.196.30.123:3306)/user_service?charset=utf8&parseTime=True&loc=Local"
micro:
  service: "userService"
  version: "latest"
server:
  http:
    host: "127.0.0.1"
    port: 8080
log:
  dir: "./log/"
user:
  avatar: ""