version: "2"
services:
  db:
    networks:
      - user_network
    restart: always
    image: mysql:8.0.29
    volumes:
      - /docker/volume/inn/user/conf/my.cnf
      - /docker/volume/inn/user/data:/var/lib/mysql
      - /docker/volume/inn/user/user.sql:/docker-entrypoint-initdb.d/user.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

  user:
    networks:
      - user_network
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    ports:
      - "8081:80"