log:
  dir: "./log/"
micro:
  service: "gateway"
  version: "latest"
gin:
  mode: "debug"
  port: ":8080"
qiniu:
  accessKey: "K97v7TLCWxyOp4bBe9RDGTmd9JHgUERY_aKeFdh6"
  secretKey: "KjNEiKwznsvfL_ceMbETWjwGDnpn1WdtvXwL2dfQ"
  bucket: "yyj-second-blog"
  prefix: "http://qny.yyj-freshman-blog.xyz/"