database:
  dsn: "root:root@tcp(db:3306)/post_service?charset=utf8&parseTime=True&loc=Local"
micro:
  service: "postService"
  version: "latest"
server:
  http:
    address: "127.0.0.1:80"
category:
  - "t1"
  - "t2"
  - "t3"
  - "t4"
  - "t5"