database:
  dsn: "root:Root@123@tcp(139.196.30.123:3306)/inn?charset=utf8&parseTime=True&loc=Local"
micro:
  service: "postService"
  version: "latest"
server:
  http:
    address: "127.0.0.1:8082"
category:
  start: false
  region:
    - "t1"
    - "t2"
    - "t3"
    - "t4"
    - "t5"
