database:
  dsn: "root:root@tcp(139.196.30.123:3306)/post_service?charset=utf8&parseTime=True&loc=Local"
micro:
  service: "postService"
  version: "latest"
server:
  http:
    address: "127.0.0.1:8082"
log:
  dir: "./log/"
category:
  - "t1"
  - "t2"
  - "t3"
  - "t4"
  - "t5"